Tks 385 chilliz erc 20 support tkn bc
TokenScript/token-negotiator pull request #538
Opened 2023-02-01 12:48 UTC by BankiLouis

2023-02-09 06:49 UTC, micwallace requested changes
@BankiLouis Please remove .sass-cache folder from git and add to .gitignore so it is never checked in again. Please review files before commit to ensure no unnecessary changes have been added.

2023-02-13 10:12 UTC, micwallace commented
Additional issues:
- Navigate to tokens list screen is broken - clicking causes error
- Many calls to `http://localhost:3010/null` happening, haven't pinpointed why

The USX polygon examples is somehow being expanded to three separate tokens, as per your screenshot above:
```
{
	onChain: true,
	fungible: true,
	collectionID: "polygon",
	contract: '0x52459834ca561cb55411699e9c2143683bcf865f',
	chain: 'matic',
	blockchain: "evm",
},
```

2023-02-15 06:19 UTC, micwallace submitted a review, later dismissed

2023-02-15 06:32 UTC, BankiLouis commented on src/client/index.ts
> +				if (Object.keys(tokenData).includes('fungible') && tokenData.fungible) {
thanks, I'll update this

2023-02-15 06:39 UTC, micwallace submitted a review, later dismissed

2023-02-15 06:46 UTC, merged